# -*- coding: utf-8 -*-
"""Submit form makanan

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lTgWtX0UtYO9HM2HUOgs6BeItJegUNc7

Kode Otomasi Submit Makanan
"""
import datetime

import requests, re, json, time

FORM = "https://docs.google.com/forms/d/e/1FAIpQLSd0TFLM7S9QmunvL0BNNZFgjgPHJsqljAaXnTOlY5qBO6kT9w/viewform"
POST = FORM.replace("viewform", "formResponse")

NAMES = ["Cory","Rudi","Dharma","Aldi","Fariz M","Almas","Sabam","Indah", "Bu Yayah", "Milia"]

s = requests.Session()

html = s.get(FORM).text
match = re.search(r"FB_PUBLIC_LOAD_DATA_ = (.*?);</script>", html)

if match:
    try:
        data = json.loads(match.group(1))
    except Exception as e:
        print("❌ GAGAL parsing JSON:", e)
        exit(0)
else:
    print("❌ GAGAL: data form tidak ditemukan (regex tidak cocok)")
    exit(0)

makanan_list = []
makanan_id = None

for i in data[1][1]:
    if not i or not i[4]: continue

    label = (i[1] or "").lower()
    e = i[4][0]

    # lebih fleksibel: cukup cari kata "makan"
    if "makan" in label:
        makanan_id = e[0]

        if len(e) > 1 and e[1]:
            makanan_list = [x[0] for x in e[1]]

print("Menu terdeteksi:", makanan_list)

# VALIDASI WAJIB
if not makanan_list:
    raise Exception("Gagal detect menu makanan. Cek label atau struktur form berubah.")

for i, n in enumerate(NAMES, 1):
    makanan = makanan_list[i % len(makanan_list)]

    payload = {
        "entry.345226776": n,
        "entry.1601379473": "IAU 4",
        f"entry.{makanan_id}": makanan,
        "pageHistory": "0,1",
        "fvv": "1"
    }

    r = s.post(POST, data=payload)

    status = "TERKIRIM" if r.status_code == 200 else f"GAGAL ({r.status_code})"
    print(f"{i}. {n} | {makanan} -> {status}")

    time.sleep(0.7)

print("RUN AT:", datetime.datetime.now())