name: Auto Submit Form
on:
  schedule:
  - cron: '50 8 * * 1-5'   # 15:50 WIB
  - cron: '10 9 * * 1-5'   # 16:10 WIB
  - cron: '20 9 * * 1-5'   # 16:20 WIB
  workflow_dispatch: # 17:20 WIB 


env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          TZ: 'Asia/Jakarta'
        run: python submit_form_makanan.py
